package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"text/tabwriter"

	"github.com/shakestzd/wipnote/internal/blame"
	"github.com/spf13/cobra"
)

// codeAreasOpts holds the parsed CLI flags for `wipnote code-areas`.
type codeAreasOpts struct {
	format           string
	root             string
	byFile           bool
	includeUntracked bool
}

// codeAreasCmd returns the cobra command for `wipnote code-areas`.
func codeAreasCmd() *cobra.Command {
	var opts codeAreasOpts

	cmd := &cobra.Command{
		Use:   "code-areas",
		Short: "Aggregate file→track attribution across the codebase",
		Long: `Walks every tracked source file under --root, runs the blame query
for each, and emits a per-track inventory.

Modes:
  --by-track (default): group files by their dominant track
  --by-file:            inverse — list each file with its tracks

Output formats: text (default), json, markdown

Examples:
  wipnote code-areas
  wipnote code-areas --format markdown
  wipnote code-areas --by-file --format json
  wipnote code-areas --root /path/to/project`,
		Args: cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			return runCodeAreas(opts)
		},
	}

	cmd.Flags().StringVar(&opts.format, "format", "text", "output format: text, json, or markdown")
	cmd.Flags().StringVar(&opts.root, "root", "", "root directory to walk (default: repo root)")
	cmd.Flags().BoolVar(&opts.byFile, "by-file", false, "inverse mode: list each file with its tracks")
	cmd.Flags().BoolVar(&opts.includeUntracked, "include-untracked", true, "include files with no feature attribution")

	return cmd
}

// runCodeAreas opens the database, calls WalkAreas, and dispatches to formatter.
func runCodeAreas(opts codeAreasOpts) error {
	dir, err := findWipnoteDir()
	if err != nil {
		return err
	}

	root := opts.root
	if root == "" {
		root = filepath.Dir(dir)
	}

	database, err := openDB(dir)
	if err != nil {
		return err
	}
	defer database.Close()

	inc := opts.includeUntracked
	walkOpts := blame.WalkOptions{
		ByFile:           opts.byFile,
		IncludeUntracked: &inc,
	}

	result, err := blame.WalkAreas(context.Background(), database, root, walkOpts)
	if err != nil {
		return fmt.Errorf("code-areas walk: %w", err)
	}

	switch opts.format {
	case "json":
		data, marshalErr := json.MarshalIndent(result, "", "  ")
		if marshalErr != nil {
			return fmt.Errorf("format json: %w", marshalErr)
		}
		fmt.Println(string(data))
	case "markdown":
		fmt.Print(formatAreasMarkdown(result, opts.byFile))
	case "text", "":
		fmt.Print(formatAreasText(result, opts.byFile))
	default:
		return fmt.Errorf("unknown format %q: use text, json, or markdown", opts.format)
	}

	return nil
}

// formatAreasText renders the AreasResult as a human-readable table.
func formatAreasText(r *blame.AreasResult, byFile bool) string {
	var buf bytes.Buffer
	sep := strings.Repeat("─", 60)

	if byFile {
		fmt.Fprintf(&buf, "%s\n  Code Areas — by file\n%s\n\n", sep, sep)
		if len(r.ByFile) == 0 {
			fmt.Fprintln(&buf, "  No attributed files found.")
		} else {
			tw := tabwriter.NewWriter(&buf, 0, 0, 2, ' ', 0)
			fmt.Fprintln(tw, "  File\tTracks\tTouches")
			for _, fa := range r.ByFile {
				total := 0
				for _, tr := range fa.Tracks {
					total += tr.TouchCount
				}
				fmt.Fprintf(tw, "  %s\t%d\t%d\n", fa.Path, len(fa.Tracks), total)
			}
			tw.Flush()
		}
	} else {
		fmt.Fprintf(&buf, "%s\n  Code Areas — by track\n%s\n\n", sep, sep)
		if len(r.ByTrack) == 0 {
			fmt.Fprintln(&buf, "  No attributed files found.")
		} else {
			for _, ta := range r.ByTrack {
				fmt.Fprintf(&buf, "  Track: %s (%s)  files=%d touches=%d\n",
					ta.TrackTitle, ta.TrackID, len(ta.Files), ta.TouchCount)
				tw := tabwriter.NewWriter(&buf, 0, 0, 2, ' ', 0)
				fmt.Fprintln(tw, "    File\tFeatures\tTouches")
				for _, f := range ta.Files {
					fmt.Fprintf(tw, "    %s\t%d\t%d\n", f.Path, f.Features, f.Touches)
				}
				tw.Flush()
				fmt.Fprintln(&buf)
			}
		}
	}

	if len(r.Untracked) > 0 {
		fmt.Fprintf(&buf, "  Untracked: %d files\n", len(r.Untracked))
	}

	return buf.String()
}

// formatAreasMarkdown renders the AreasResult as a drop-in reference document.
func formatAreasMarkdown(r *blame.AreasResult, byFile bool) string {
	var buf bytes.Buffer

	fmt.Fprintln(&buf, "# Code Areas")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "_Snapshot generated by `wipnote code-areas --format markdown`._")
	fmt.Fprintln(&buf, "_Re-run that command locally to refresh; not enforced in CI because attribution_")
	fmt.Fprintln(&buf, "_depends on local feature_files state that the canonical `.wipnote/*.html` does not yet carry._")
	fmt.Fprintln(&buf)

	if byFile {
		fmt.Fprintln(&buf, "## Files")
		fmt.Fprintln(&buf)
		if len(r.ByFile) == 0 {
			fmt.Fprintln(&buf, "_No attributed files found._")
		} else {
			fmt.Fprintln(&buf, "| File | Tracks | Touches |")
			fmt.Fprintln(&buf, "|------|--------|---------|")
			for _, fa := range r.ByFile {
				total := 0
				for _, tr := range fa.Tracks {
					total += tr.TouchCount
				}
				fmt.Fprintf(&buf, "| %s | %d | %d |\n", fa.Path, len(fa.Tracks), total)
			}
		}
		fmt.Fprintln(&buf)
	} else {
		if len(r.ByTrack) == 0 {
			fmt.Fprintln(&buf, "_No attributed files found._")
		} else {
			for _, ta := range r.ByTrack {
				fmt.Fprintf(&buf, "## Track: %s (%s)\n\n", ta.TrackTitle, ta.TrackID)
				fmt.Fprintf(&buf, "%d features, %d files, %d total touches\n\n",
					ta.FeatureCount, len(ta.Files), ta.TouchCount)
				fmt.Fprintln(&buf, "| File | Features | Touches |")
				fmt.Fprintln(&buf, "|------|----------|---------|")
				for _, f := range ta.Files {
					fmt.Fprintf(&buf, "| %s | %d | %d |\n", f.Path, f.Features, f.Touches)
				}
				fmt.Fprintln(&buf)
			}
		}
	}

	if len(r.Untracked) > 0 {
		fmt.Fprintln(&buf, "## Untracked")
		fmt.Fprintln(&buf)
		fmt.Fprintf(&buf, "%d files with no feature attribution.\n\n", len(r.Untracked))
		for _, u := range r.Untracked {
			fmt.Fprintf(&buf, "- %s\n", u)
		}
		fmt.Fprintln(&buf)
	}

	return buf.String()
}
