package main

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// shellAliasCmd prints opt-in shell aliases that route the bare harness
// commands (claude, codex, gemini) through their wipnote wrappers. Users
// can pipe the output into their shell or paste it into ~/.bashrc /
// ~/.zshrc to globally activate wipnote without per-project invocation.
//
// This is intentionally NOT auto-installed: per-project `wipnote claude`
// remains the recommended flow because it avoids surprising shell behavior
// for users in non-wipnote projects.
func shellAliasCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "shell-alias",
		Short: "Print opt-in shell aliases for claude/codex/gemini",
		Long: `Print opt-in shell aliases that route bare harness commands through wipnote.

Per-project invocation (wipnote claude / wipnote codex / wipnote gemini) is the
recommended flow. These aliases are for users who want global activation.

To install, append the output to your shell rc file:

  wipnote shell-alias >> ~/.bashrc    # bash
  wipnote shell-alias >> ~/.zshrc     # zsh

Or pipe directly into the current shell session (one-shot):

  eval "$(wipnote shell-alias)"

Output is plain shell, safe to run multiple times.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			fmt.Fprint(os.Stdout, shellAliasSnippet())
			return nil
		},
	}
}

// shellAliasSnippet is the text written by `wipnote shell-alias`. Plain
// POSIX-compatible alias syntax (works in bash and zsh).
func shellAliasSnippet() string {
	return `# wipnote shell-alias — opt-in global activation
# Routes bare 'claude', 'codex', and 'gemini' through their wipnote launchers.
# Generated by: wipnote shell-alias
alias claude='wipnote claude'
alias codex='wipnote codex'
alias gemini='wipnote gemini'
`
}
