// Register in main.go: rootCmd.AddCommand(specCmd())
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"

	"github.com/shakestzd/wipnote/internal/htmlparse"
	"github.com/shakestzd/wipnote/internal/models"
	"github.com/shakestzd/wipnote/internal/planyaml"
	"github.com/shakestzd/wipnote/internal/workitem"
	"github.com/spf13/cobra"
)

const specAttributionComment = "<!-- Spec generated by wipnote spec generate. See plugin/templates/spec-template.md (OpenSpec MIT). -->"

// specRequirement is one RFC 2119 requirement with at least one Given/When/Then scenario.
type specRequirement struct {
	Name      string         `json:"name"`
	SHALL     string         `json:"shall"`
	Scenarios []specScenario `json:"scenarios"`
}

// specScenario is one Given/When/Then scenario block.
type specScenario struct {
	Name string `json:"name"`
	When string `json:"when"`
	Then string `json:"then"`
}

// specTemplate holds the structured fields of a feature spec.
//
// New (OpenSpec) format consumes Requirements + DecisionsNotes; legacy callers
// that still set AcceptanceCriteria fall through to the legacy renderer.
type specTemplate struct {
	FeatureID          string            `json:"feature_id"`
	Title              string            `json:"title"`
	Problem            string            `json:"problem"`
	DecisionsNotes     string            `json:"decisions_notes,omitempty"`
	Requirements       []specRequirement `json:"requirements,omitempty"`
	AcceptanceCriteria []string          `json:"acceptance_criteria,omitempty"`
	Files              []string          `json:"files"`
	APISurface         []string          `json:"api_surface,omitempty"`
	Notes              []string          `json:"notes"`
}

func specCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "spec",
		Short: "Manage specs and feature specifications",
		Long:  "Create spec work items and generate structured spec templates for features.",
	}
	// Spec work item CRUD
	cmd.AddCommand(wiCreateCmd("spec", "specs"))
	cmd.AddCommand(wiListCmd("spec", "specs"))
	cmd.AddCommand(wiStartCmd("spec"))
	cmd.AddCommand(wiCompleteCmd("spec"))
	cmd.AddCommand(wiDeleteCmd("spec"))
	// Spec template generation (feature-specific)
	cmd.AddCommand(specGenerateCmd())
	cmd.AddCommand(specShowCmd())
	return cmd
}

func specGenerateCmd() *cobra.Command {
	var format, output string
	var insert, force bool

	cmd := &cobra.Command{
		Use:   "generate <feature-id>",
		Short: "Generate a spec template for a feature",
		Args:  cobra.ExactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			return runSpecGenerate(args[0], format, output, insert, force)
		},
	}
	cmd.Flags().StringVar(&format, "format", "markdown", "Output format: markdown or json")
	cmd.Flags().StringVar(&output, "output", "", "Write output to file instead of stdout (mutually exclusive with --insert)")
	cmd.Flags().BoolVar(&insert, "insert", false, "Write the generated spec into the feature HTML's <section class=\"spec\"> block")
	cmd.Flags().BoolVar(&force, "force", false, "With --insert, overwrite an existing non-empty spec section")
	return cmd
}

func specShowCmd() *cobra.Command {
	var format, output string

	cmd := &cobra.Command{
		Use:   "show <feature-id>",
		Short: "Show the spec for a feature if one exists",
		Args:  cobra.ExactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			return runSpecShow(args[0], format, output)
		},
	}
	cmd.Flags().StringVar(&format, "format", "markdown", "Output format: markdown or json")
	cmd.Flags().StringVar(&output, "output", "", "Write output to file instead of stdout")
	return cmd
}

// runSpecGenerate builds a spec template for a feature and either prints it,
// writes it to a file, or inserts it into the feature HTML.
func runSpecGenerate(featureID, format, output string, insert, force bool) error {
	if insert && output != "" {
		return errors.New("--insert and --output are mutually exclusive; pick one")
	}
	if format != "markdown" && format != "json" {
		return fmt.Errorf("unknown format %q (markdown or json)", format)
	}
	if insert && format == "json" {
		return errors.New("--insert writes Markdown into the feature HTML; --format=json is incompatible")
	}

	dir, err := findWipnoteDir()
	if err != nil {
		return err
	}

	featurePath := filepath.Join(dir, "features", featureID+".html")
	node, err := htmlparse.ParseFile(featurePath)
	if err != nil {
		if os.IsNotExist(err) {
			return workitem.ErrNotFound("feature", featureID)
		}
		return fmt.Errorf("parse feature %s: %w", featureID, err)
	}

	spec := buildSpecFromFeature(featureID, node, dir)

	if insert {
		return insertSpecIntoFeature(featurePath, spec, force)
	}

	var content string
	switch format {
	case "json":
		data, jerr := json.MarshalIndent(spec, "", "  ")
		if jerr != nil {
			return fmt.Errorf("marshal spec: %w", jerr)
		}
		content = string(data)
	default:
		content = renderSpecMarkdown(spec)
	}
	return writeOutput(content, output)
}

// runSpecShow looks for an existing spec section in the feature HTML.
func runSpecShow(featureID, format, output string) error {
	dir, err := findWipnoteDir()
	if err != nil {
		return err
	}

	path := filepath.Join(dir, "features", featureID+".html")
	if _, err := os.Stat(path); err != nil {
		return workitem.ErrNotFound("feature", featureID)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read feature file: %w", err)
	}

	specContent := extractSpecSection(string(content))
	if specContent == "" {
		fmt.Printf("No spec found. Run: wipnote spec generate %s\n", featureID)
		return nil
	}

	if format == "json" {
		return writeOutput(buildSpecJSON(featureID, specContent), output)
	}
	return writeOutput(specContent, output)
}

// buildSpecFromFeature assembles a spec template, preferring slice-derived
// fields when the feature is linked to a plan, falling back to a blank
// template otherwise.
func buildSpecFromFeature(featureID string, node *models.Node, wipnoteDir string) *specTemplate {
	spec := &specTemplate{
		FeatureID: featureID,
		Title:     node.Title,
		Problem:   "What problem does this solve? Why is it needed?",
		Files:     []string{"NEW: path/to/new/file.go", "EDIT: path/to/existing/file.go"},
		Notes:     []string{"Dependencies, risks, edge cases"},
	}

	slice := lookupSliceForFeature(node, wipnoteDir, featureID)
	if slice == nil {
		spec.AcceptanceCriteria = []string{"Criterion 1", "Criterion 2", "Criterion 3"}
		spec.APISurface = []string{"Function/command signatures", "Input/output formats"}
		return spec
	}

	if w := strings.TrimSpace(slice.Why); w != "" {
		spec.Problem = w
	}
	if dn := sliceDecisionsNotes(slice); dn != "" {
		spec.DecisionsNotes = dn
	}
	if len(slice.Files) > 0 {
		spec.Files = append([]string(nil), slice.Files...)
	}
	if t := strings.TrimSpace(slice.Tests); t != "" {
		spec.Notes = []string{t}
	}
	spec.Requirements = buildRequirementsFromDoneWhen(slice.DoneWhen, slice.Tests)
	return spec
}

// lookupSliceForFeature finds the PlanSlice corresponding to a feature by
// following the planned_in edge to the plan YAML and matching feature_id.
// Returns nil if the feature has no plan link or the slice is not found.
func lookupSliceForFeature(node *models.Node, wipnoteDir, featureID string) *planyaml.PlanSlice {
	planID := ""
	if edges, ok := node.Edges["planned_in"]; ok && len(edges) > 0 {
		planID = edges[0].TargetID
	}
	if planID == "" {
		return nil
	}
	planPath := filepath.Join(wipnoteDir, "plans", planID+".yaml")
	plan, err := planyaml.Load(planPath)
	if err != nil {
		return nil
	}
	for i := range plan.Slices {
		if plan.Slices[i].FeatureID == featureID {
			return &plan.Slices[i]
		}
	}
	return nil
}

// sliceDecisionsNotes reads the optional DecisionsNotes field from a PlanSlice.
// Uses reflection so we keep working before slice 3 ships the typed field —
// the renderer treats absence and empty as identical.
func sliceDecisionsNotes(slice *planyaml.PlanSlice) string {
	if slice == nil {
		return ""
	}
	v := reflect.ValueOf(slice).Elem()
	f := v.FieldByName("DecisionsNotes")
	if !f.IsValid() || f.Kind() != reflect.String {
		return ""
	}
	return strings.TrimSpace(f.String())
}

// buildRequirementsFromDoneWhen turns a slice's done_when entries into
// OpenSpec-formatted requirements with a single placeholder scenario each.
func buildRequirementsFromDoneWhen(doneWhen []string, tests string) []specRequirement {
	if len(doneWhen) == 0 {
		return nil
	}
	out := make([]specRequirement, 0, len(doneWhen))
	for i, dw := range doneWhen {
		dw = strings.TrimSpace(dw)
		if dw == "" {
			continue
		}
		req := specRequirement{
			Name:  fmt.Sprintf("Requirement %d", i+1),
			SHALL: dw,
			Scenarios: []specScenario{
				{
					Name: "implementation satisfies the criterion",
					When: "the implementation is reviewed against this requirement",
					Then: "the criterion above is fully satisfied",
				},
			},
		}
		out = append(out, req)
	}
	if len(out) > 0 && strings.TrimSpace(tests) != "" {
		// Attach the slice's tests prose to the first requirement as a hint.
		out[0].Scenarios[0].Then = strings.TrimSpace(tests)
	}
	return out
}

// renderSpecMarkdown formats the spec as a Markdown document.
//
// Render order (when Requirements present):
//
//	# Spec: <Title>
//	## Problem
//	## Decisions          (only when DecisionsNotes non-empty)
//	## ADDED Requirements
//	  ### Requirement: ...
//	    #### Scenario: ...
//	## Files
//	## Notes
//
// When Requirements is empty, falls back to the legacy `## Acceptance Criteria`
// checkbox layout for backward compatibility.
func renderSpecMarkdown(s *specTemplate) string {
	var sb strings.Builder

	sb.WriteString(specAttributionComment + "\n\n")
	sb.WriteString(fmt.Sprintf("# Spec: %s\n\n", s.Title))

	sb.WriteString("## Problem\n")
	sb.WriteString(s.Problem + "\n\n")

	if dn := strings.TrimSpace(s.DecisionsNotes); dn != "" {
		sb.WriteString("## Decisions\n")
		sb.WriteString(dn + "\n\n")
	}

	if len(s.Requirements) > 0 {
		sb.WriteString("## ADDED Requirements\n\n")
		for _, r := range s.Requirements {
			sb.WriteString(fmt.Sprintf("### Requirement: %s\n", r.Name))
			sb.WriteString("The implementation SHALL ensure: " + r.SHALL + "\n\n")
			for _, sc := range r.Scenarios {
				sb.WriteString(fmt.Sprintf("#### Scenario: %s\n", sc.Name))
				sb.WriteString(fmt.Sprintf("- **WHEN** %s\n", sc.When))
				sb.WriteString(fmt.Sprintf("- **THEN** %s\n\n", sc.Then))
			}
		}
	} else {
		sb.WriteString("## Acceptance Criteria\n")
		for i, c := range s.AcceptanceCriteria {
			sb.WriteString(fmt.Sprintf("%d. [ ] %s\n", i+1, c))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Files\n")
	for _, f := range s.Files {
		sb.WriteString(fmt.Sprintf("- %s\n", f))
	}
	sb.WriteString("\n")

	if len(s.APISurface) > 0 {
		sb.WriteString("## API Surface\n")
		for _, a := range s.APISurface {
			sb.WriteString(fmt.Sprintf("- %s\n", a))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## Notes\n")
	for _, n := range s.Notes {
		sb.WriteString(fmt.Sprintf("- %s\n", n))
	}

	return sb.String()
}

// extractSpecSection looks for <section class="spec"> inside feature HTML and
// returns its inner content trimmed of surrounding whitespace.
func extractSpecSection(html string) string {
	const open = `<section class="spec">`
	const close = `</section>`

	start := strings.Index(html, open)
	if start == -1 {
		return ""
	}
	end := strings.Index(html[start:], close)
	if end == -1 {
		return ""
	}
	inner := html[start+len(open) : start+end]
	return strings.TrimSpace(inner)
}

// specSectionIsEmpty returns true when the spec section is missing OR contains
// only the attribution comment + whitespace. This is what `--insert` checks
// before refusing to clobber.
func specSectionIsEmpty(html string) bool {
	inner := extractSpecSection(html)
	if inner == "" {
		return true
	}
	stripped := strings.TrimSpace(strings.ReplaceAll(inner, specAttributionComment, ""))
	return stripped == ""
}

// insertSpecIntoFeature writes the rendered spec into the feature HTML's
// <section class="spec"> block, refusing to clobber non-empty content unless
// force is set. Acquires workitem.LockFeatureForWrite (in-process mutex +
// cross-process flock) for the entire RMW window so concurrent compliance
// auto writers — including from other `wipnote` CLI processes — cannot
// lose updates.
func insertSpecIntoFeature(featurePath string, spec *specTemplate, force bool) error {
	defer workitem.LockFeatureForWrite(featurePath)()

	raw, err := os.ReadFile(featurePath)
	if err != nil {
		return fmt.Errorf("read feature file: %w", err)
	}
	html := string(raw)

	rendered := renderSpecMarkdown(spec)

	if !specSectionIsEmpty(html) && !force {
		existing := extractSpecSection(html)
		fmt.Fprintln(os.Stderr, "spec section already has content; pass --force to overwrite, or edit the section directly")
		fmt.Fprintln(os.Stderr, unifiedDiff(existing, rendered))
		return errors.New("spec section already has content; pass --force to overwrite")
	}

	updated := replaceOrAppendSpecSection(html, rendered)
	if err := writeFileAtomicRaw(featurePath, []byte(updated)); err != nil {
		return err
	}
	fmt.Printf("Spec written to %s\n", featurePath)
	return nil
}

// replaceOrAppendSpecSection replaces an existing <section class="spec"> or
// inserts a new one before </body>. The Markdown body is wrapped in a
// <pre>...</pre> block to round-trip cleanly through htmlparse.
func replaceOrAppendSpecSection(html, rendered string) string {
	sectionHTML := `<section class="spec">` + "\n<pre>\n" +
		escapeForPre(rendered) + "</pre>\n</section>"

	const openTag = `<section class="spec">`
	const closeTag = `</section>`

	start := strings.Index(html, openTag)
	if start == -1 {
		bodyClose := strings.LastIndex(html, "</body>")
		if bodyClose == -1 {
			return html + "\n" + sectionHTML + "\n"
		}
		return html[:bodyClose] + sectionHTML + "\n" + html[bodyClose:]
	}

	afterOpen := html[start:]
	end := strings.Index(afterOpen, closeTag)
	if end == -1 {
		return html[:start] + sectionHTML
	}
	end += start + len(closeTag)
	return html[:start] + sectionHTML + html[end:]
}

// escapeForPre escapes the three characters that must not appear raw inside
// a <pre> element. Keeps the Markdown verbatim otherwise.
func escapeForPre(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;")
	return r.Replace(s)
}

// unifiedDiff returns a tiny line-level diff between old and new. It is not
// the GNU `diff -u` format but is recognisable enough for the user to act on,
// and avoids a runtime dependency.
func unifiedDiff(oldText, newText string) string {
	var sb strings.Builder
	sb.WriteString("--- existing spec section\n+++ rendered spec\n")
	oldLines := strings.Split(strings.TrimRight(oldText, "\n"), "\n")
	newLines := strings.Split(strings.TrimRight(newText, "\n"), "\n")
	for _, l := range oldLines {
		sb.WriteString("- " + l + "\n")
	}
	for _, l := range newLines {
		sb.WriteString("+ " + l + "\n")
	}
	return sb.String()
}

// buildSpecJSON wraps raw spec content in a minimal JSON envelope.
func buildSpecJSON(featureID, content string) string {
	m := map[string]string{
		"feature_id": featureID,
		"spec":       content,
	}
	data, _ := json.MarshalIndent(m, "", "  ")
	return string(data)
}

// writeOutput writes content to a file or stdout.
func writeOutput(content, path string) error {
	if path == "" {
		fmt.Println(content)
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Printf("Spec written to %s\n", path)
	return nil
}

// thirdPartyNoticesPattern matches the OpenSpec entry in the repo-root notices file.
var thirdPartyNoticesPattern = regexp.MustCompile(`(?s)OpenSpec.*MIT`)
