package pluginbuild

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestCodexMarketplaceJSONEmitted checks that marketplace.json is written at
// <outDir>/.agents/plugins/marketplace.json with the required fields: non-empty
// name, non-empty plugins[], and source.path starting with "./" (relative to
// the .agents/plugins/ directory, so just the plugin name, not the full subdir).
func TestCodexMarketplaceJSONEmitted(t *testing.T) {
	repoRoot := t.TempDir()
	seedAssets(t, repoRoot)
	outDir := filepath.Join(repoRoot, "packages", "codex-marketplace")

	if err := (codexAdapter{}).Emit(fixtureManifest(), repoRoot, outDir); err != nil {
		t.Fatalf("Emit: %v", err)
	}

	mktPath := filepath.Join(outDir, ".agents", "plugins", "marketplace.json")
	data, err := os.ReadFile(mktPath)
	if err != nil {
		t.Fatalf("read marketplace.json at %s: %v", mktPath, err)
	}

	// marketplace.json must NOT exist at the old outDir root location.
	oldPath := filepath.Join(outDir, "marketplace.json")
	if _, err := os.Stat(oldPath); !os.IsNotExist(err) {
		t.Errorf("marketplace.json must NOT exist at outDir root %q", oldPath)
	}

	var mkt codexMarketplaceJSON
	if err := json.Unmarshal(data, &mkt); err != nil {
		t.Fatalf("unmarshal marketplace.json: %v", err)
	}

	if mkt.Name == "" {
		t.Error("marketplace.json: name must not be empty")
	}
	if len(mkt.Plugins) == 0 {
		t.Fatal("marketplace.json: plugins[] must not be empty")
	}
	plug := mkt.Plugins[0]
	if plug.Name == "" {
		t.Error("marketplace.json: plugins[0].name must not be empty")
	}
	if !strings.HasPrefix(plug.Source.Path, "./") {
		t.Errorf("marketplace.json: plugins[0].source.path must start with \"./\", got %q", plug.Source.Path)
	}
	if plug.Source.Source != "local" {
		t.Errorf("marketplace.json: plugins[0].source.source must be \"local\", got %q", plug.Source.Source)
	}
	if mkt.Interface.DisplayName == "" {
		t.Error("marketplace.json: interface.displayName must not be empty")
	}
}

// TestCodexPluginTreeUnderPluginsSubdir verifies that the plugin manifest lives
// at .agents/plugins/htmlgraph/.codex-plugin/plugin.json (inside the marketplace
// tree), not at the marketplace root. Codex reads marketplace.json from
// .agents/plugins/ and expects plugin content in a sibling subdirectory.
func TestCodexPluginTreeUnderPluginsSubdir(t *testing.T) {
	repoRoot := t.TempDir()
	seedAssets(t, repoRoot)
	outDir := filepath.Join(repoRoot, "packages", "codex-marketplace")

	if err := (codexAdapter{}).Emit(fixtureManifest(), repoRoot, outDir); err != nil {
		t.Fatalf("Emit: %v", err)
	}

	pluginManifest := filepath.Join(outDir, ".agents", "plugins", "htmlgraph", ".codex-plugin", "plugin.json")
	if _, err := os.Stat(pluginManifest); err != nil {
		t.Fatalf(".codex-plugin/plugin.json not found at expected path %q: %v", pluginManifest, err)
	}

	// Verify the file is NOT at the old flat root location.
	oldPath := filepath.Join(outDir, ".codex-plugin", "plugin.json")
	if _, err := os.Stat(oldPath); !os.IsNotExist(err) {
		t.Errorf("plugin.json should NOT exist at marketplace root %q (got stat err=%v)", oldPath, err)
	}

	// Verify the file is NOT at the old (pre-.agents) plugins/ location.
	oldPluginsPath := filepath.Join(outDir, "plugins", "htmlgraph", ".codex-plugin", "plugin.json")
	if _, err := os.Stat(oldPluginsPath); !os.IsNotExist(err) {
		t.Errorf("plugin.json should NOT exist at old plugins/ path %q (got stat err=%v)", oldPluginsPath, err)
	}

	// Confirm plugin content is parseable.
	var plug codexPluginJSON
	readJSON(t, pluginManifest, &plug)
	if plug.Name == "" || plug.Version == "" {
		t.Errorf("plugin.json missing name/version: %+v", plug)
	}
}

// TestCodexAdapterRemovesStaleFilesMarketplace verifies that stale-file cleanup
// works correctly for the marketplace layout. The owned subtree is narrowed to
// .agents/plugins/htmlgraph/; leftovers under htmlgraph/ must be removed, but
// sibling plugins and marketplace.json under .agents/plugins/ must survive.
// marketplace.json is regenerated by Emit.
func TestCodexAdapterRemovesStaleFilesMarketplace(t *testing.T) {
	repoRoot := t.TempDir()
	seedAssets(t, repoRoot)
	outDir := filepath.Join(repoRoot, "packages", "codex-marketplace")

	// Seed a stale file deep inside the .agents/plugins/htmlgraph/ owned subtree.
	staleFile := filepath.Join(outDir, ".agents", "plugins", "htmlgraph", "commands", "stale-cmd.md")
	if err := os.MkdirAll(filepath.Dir(staleFile), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(staleFile, []byte("stale content"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Seed a stale directory (simulating a renamed agent).
	staleDir := filepath.Join(outDir, ".agents", "plugins", "htmlgraph", "agents", "old-agent")
	if err := os.MkdirAll(staleDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(staleDir, "README.md"), []byte("old"), 0o644); err != nil {
		t.Fatal(err)
	}

	// Seed a sibling plugin under .agents/plugins/ to verify it survives rebuild.
	siblingFile := filepath.Join(outDir, ".agents", "plugins", "other-plugin", "dummy.txt")
	if err := os.MkdirAll(filepath.Dir(siblingFile), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(siblingFile, []byte("sibling plugin content"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := (codexAdapter{}).Emit(fixtureManifest(), repoRoot, outDir); err != nil {
		t.Fatalf("Emit: %v", err)
	}

	// Stale command file must be gone (.agents/plugins/htmlgraph/ subtree was fully cleaned).
	if _, err := os.Stat(staleFile); !os.IsNotExist(err) {
		t.Errorf("expected stale command file to be removed; stat err=%v", err)
	}
	// Stale agent dir must be gone.
	if _, err := os.Stat(staleDir); !os.IsNotExist(err) {
		t.Errorf("expected stale agent dir to be removed; stat err=%v", err)
	}

	// Sibling plugin must STILL EXIST (cleanup was narrowed to htmlgraph/ only).
	if _, err := os.Stat(siblingFile); err != nil {
		t.Errorf("expected sibling plugin file to survive rebuild; stat err=%v", err)
	}

	// marketplace.json must exist after Emit (regenerated inside .agents/plugins/).
	mktPath := filepath.Join(outDir, ".agents", "plugins", "marketplace.json")
	if _, err := os.Stat(mktPath); err != nil {
		t.Errorf("marketplace.json must exist after Emit at %s: %v", mktPath, err)
	}
}

// TestCodexMarketplaceSourcePathForNestedSubdir verifies that source.path is
// computed correctly when pluginSubdir is nested deeper than the default
// .agents/plugins/htmlgraph. The path should be relative to .agents/plugins/
// and use forward slashes.
func TestCodexMarketplaceSourcePathForNestedSubdir(t *testing.T) {
	repoRoot := t.TempDir()
	seedAssets(t, repoRoot)
	outDir := filepath.Join(repoRoot, "packages", "codex-marketplace")

	// Create a manifest with a nested pluginSubdir.
	m := fixtureManifest()
	// Can't assign to map value directly, so create new targets map.
	codexTarget := m.Targets["codex"]
	codexTarget.PluginSubdir = ".agents/plugins/nested/htmlgraph"
	m.Targets["codex"] = codexTarget

	if err := (codexAdapter{}).Emit(m, repoRoot, outDir); err != nil {
		t.Fatalf("Emit with nested subdir: %v", err)
	}

	// Read marketplace.json and verify source.path reflects the nested path.
	mktPath := filepath.Join(outDir, ".agents", "plugins", "marketplace.json")
	data, err := os.ReadFile(mktPath)
	if err != nil {
		t.Fatalf("read marketplace.json: %v", err)
	}

	var mkt codexMarketplaceJSON
	if err := json.Unmarshal(data, &mkt); err != nil {
		t.Fatalf("unmarshal marketplace.json: %v", err)
	}

	if len(mkt.Plugins) == 0 {
		t.Fatal("marketplace.json: plugins[] must not be empty")
	}
	plug := mkt.Plugins[0]
	expected := "./nested/htmlgraph"
	if plug.Source.Path != expected {
		t.Errorf("plugins[0].source.path = %q, want %q", plug.Source.Path, expected)
	}

	// Verify the plugin tree actually exists at the nested location.
	pluginManifest := filepath.Join(outDir, ".agents", "plugins", "nested", "htmlgraph", ".codex-plugin", "plugin.json")
	if _, err := os.Stat(pluginManifest); err != nil {
		t.Errorf("expected plugin manifest at nested path %q: %v", pluginManifest, err)
	}
}

// TestCodexPluginJSONDeclaresSkillsPath verifies that the generated plugin.json
// includes the "skills": "./skills/" field, which tells Codex's TUI where to find
// SKILL.md files for mention autocomplete (e.g., $htmlgraph or $skill-name).
func TestCodexPluginJSONDeclaresSkillsPath(t *testing.T) {
	repoRoot := t.TempDir()
	seedAssets(t, repoRoot)
	outDir := filepath.Join(repoRoot, "packages", "codex-marketplace")

	if err := (codexAdapter{}).Emit(fixtureManifest(), repoRoot, outDir); err != nil {
		t.Fatalf("Emit: %v", err)
	}

	pluginManifest := filepath.Join(outDir, ".agents", "plugins", "htmlgraph", ".codex-plugin", "plugin.json")
	var plug codexPluginJSON
	readJSON(t, pluginManifest, &plug)

	if plug.Skills != "./skills/" {
		t.Errorf("plugin.json skills field = %q, want %q", plug.Skills, "./skills/")
	}
}
